from .person_detection.person_detection import personDetectionModel
from .ppe_detection.ppe_detection import ppeDetectionModel
from .person_counting_in_zone.person_counting_in_zone import personCountInZone
from .fall_detection.fall_detection import fallDetectionModel
from .firesmokedetection.firesmokedetection import FireSmokeDetectionModel
from .garbage_detection.garbage_detection import garbageDetectionModel
from .trip_hazard_detection.triphazarddetection import triphazardDetectionModel
from .spill_detection.spill_detection import spillDetectionModel
from models.reid.reid import reID

